# Generated by Django 5.1.3 on 2025-03-16 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_payment_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='applicable_products',
            field=models.ManyToManyField(blank=True, to='core.item'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='max_uses',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='coupon',
            name='max_uses_per_user',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='coupon',
            name='product_specific',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coupon',
            name='valid_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='valid_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
