# Generated by Django 5.1.3 on 2025-03-16 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_coupon_active_coupon_applicable_products_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='active',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='applicable_products',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='max_uses',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='max_uses_per_user',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='product_specific',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='valid_from',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='valid_to',
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(max_length=15),
        ),
    ]
