# Generated by Django 5.1.3 on 2025-03-25 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_item_about_doctor_item_clinic_photos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='clinic_photos',
        ),
        migrations.CreateModel(
            name='ClinicPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='clinic_photos/')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_photos', to='core.item')),
            ],
        ),
    ]
